### ISSUE TITLE
El botón '=' no funciona como esperado

### ISSUE THREAD

**Issue by wyan** [DAMChristian/CalculadoraSWING#1]
![CalculadoraSWING_and_Calculadora_-_Apache_NetBeans_IDE_12_1](https://user-images.githubusercontent.com/121136/99574528-ce40e900-29d7-11eb-98c2-fb8a4e90c20e.png)

**Comment by Mikicchi** [comment]
Solucionado el problema gracias por comentar. :D!!!!
